version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: codevilafood-app
    volumes: 
      - ./:/var/www/html
    ports:
      - 3000:3000
    network_mode: "host"
