version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - TARGETPLATFORM=linux/amd64
    container_name: buzzin-app
    volumes: 
      - ./:/var/www/html
      - ./.docker/certs/:/etc/letsencrypt
      - ./.docker/sites-avaliable/:/etc/apache2/sites-available
    ports:
      - 80:80
      - 443:443
    entrypoint: ./run-after-build.sh
    networks:
      - app-network
    depends_on:
      - redis

  db:
    image: mysql:5.7.34
    platform: linux/amd64
    container_name: buzzin-db
    restart: always
    ports:
        - "3308:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
        - ./.docker/mysql/dbdata:/var/lib/mysql
    networks:
      - app-network

  redis:
      image: redis:latest
      platform: linux/amd64
      command: redis-server --appendonly yes --replica-read-only no
      ports:
          - "6379:6379"
      volumes: 
        - "./.docker/redis:/data"
      networks:
          - app-network
      deploy:
        replicas: 1
        resources:
          limits:
            cpus: "0.5"
            memory: 250M
          reservations:
            cpus: "0.1"
            memory: 20m
        restart_policy:
          condition: on-failure

  queue:
      build:
        context: .
        dockerfile: ./Dockerfile
        args:
        - TARGETPLATFORM=linux/amd64
      restart: always
      command: "php artisan queue:work"
      volumes:
            - ./:/var/www/html
      depends_on:
          - redis
          - app
      networks:
          - app-network

networks:
  app-network:
    driver: bridge